### PR TITLE
Use material-colors instead of google-material-color

### LINKED ISSUE #186: Fix vulnerabilities found with npm audit
Hi,
Yesterday when I installed your package I've received msg "found 1 low severity vulnerability".
Here is the screenshot:

screen shot 2018-11-08 at 09 45 10

Can you fix this please? Thanks

### PR DESCRIPTION
**Pull request by jaimesanz**
fixes #186

### CODE REVIEW

**Comment by jaimesanz** [comment]
I think this change makes sense because [material-colors](https://github.com/shuhei/material-colors) seems more maintained than [google-material-color](https://github.com/danlevan/google-material-color) (last commit was ~4 months ago vs ~2 years ago), and (as far as I know) they provide basically the same features.

**Comment by SkoricIT** [comment]
Seems like a good fix.

**Comment by m-zuro** [comment]
@riophae Can this be merged?

**Comment by enhendrickson** [comment]
@riophae when will this be merged?

**Comment by twolfvb** [comment]
Is there an ETA for this pull request?

**Comment by riophae** [comment]
Thanks for contribution! I'll release this ASAP.
Sorry for it takes so long!

**Comment by enhendrickson** [comment]
@riophae thanks!

**Pull request merged**
